package entity;
// Generated Mar 25, 2018 10:53:42 PM by Hibernate Tools 4.3.1



/**
 * Rating generated by hbm2java
 */
public class Rating  implements java.io.Serializable {


     private Integer id;
     private String username;
     private int rating;
     private String feedback;
     private String bookname;

    public Rating() {
    }

    public Rating(String username, int rating, String feedback, String bookname) {
       this.username = username;
       this.rating = rating;
       this.feedback = feedback;
       this.bookname = bookname;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public int getRating() {
        return this.rating;
    }
    
    public void setRating(int rating) {
        this.rating = rating;
    }
    public String getFeedback() {
        return this.feedback;
    }
    
    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }
    public String getBookname() {
        return this.bookname;
    }
    
    public void setBookname(String bookname) {
        this.bookname = bookname;
    }




}


