package entity;
// Generated Mar 25, 2018 10:53:42 PM by Hibernate Tools 4.3.1




/**
 * UploadBook generated by hbm2java
 */
public class UploadBook  implements java.io.Serializable {


     private Integer id;
     private String bookname;
     private String description;
     private String publishdate;
     private String publishername;
     private String selectbook;

  public UploadBook(){
   
   }

    public UploadBook(String bookname, String description, String publishdate, String publishername, String selectbook) {
       this.bookname = bookname;
       this.description = description;
       this.publishdate = publishdate;
       this.publishername = publishername;
       this.selectbook = selectbook;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getBookname() {
        return this.bookname;
    }
    
    public void setBookname(String bookname) {
        this.bookname = bookname;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getPublishdate() {
        return this.publishdate;
    }
    
    public void setPublishdate(String publishdate) {
        this.publishdate = publishdate;
    }
    public String getPublishername() {
        return this.publishername;
    }
    
    public void setPublishername(String publishername) {
        this.publishername = publishername;
    }
    public String getSelectbook() {
        return this.selectbook;
    }
    
    public void setSelectbook(String selectbook) {
        this.selectbook = selectbook;
    }




}


